steps:
  build-test:
    image: tjammer/ocaml-llvm:20260115
    commands:
      - opam install . -y --deps-only --with-test
      - opam exec -- dune build
      - ulimit -n 65536
      - opam exec -- dune test
    when:
      - event: push

  deploy:
    image: tjammer/ocaml-llvm:20260115
    commands:
      - bash .woodpecker_release.sh
    environment:
      RELEASE:
        from_secret: release
    when:
      - branch: main
        event: push
